// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from djinni_perf_benchmark.djinni
#ifdef __cplusplus
#ifndef __OBJC__

#include "EnumSixValue.hpp"
#import "DJIMarshal+Private.h"

#endif
#endif
