// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from single_language_interfaces.djinni

#pragma once

namespace testsuite {

class CppOnlyUnexposed {
public:
    virtual ~CppOnlyUnexposed() = default;
};

} // namespace testsuite
