// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_set>
#include <utility>

namespace testsuite {

struct SetRecord final {
    std::unordered_set<std::string> sset;
    std::unordered_set<int32_t> iset;

    SetRecord(std::unordered_set<std::string> sset_,
              std::unordered_set<int32_t> iset_)
    : sset(std::move(sset_))
    , iset(std::move(iset_))
    {}
};

} // namespace testsuite
