// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni
#ifdef __cplusplus
#ifndef __OBJC__

#include "sort_order.hpp"
#import "DJIMarshal+Private.h"

#endif
#endif
