// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from enum_flags.djinni
#ifdef __cplusplus
#ifndef __OBJC__

#include "access_flags.hpp"
#import "DJIMarshal+Private.h"

#endif
#endif
