// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni

#import "DBConstantEnum.h"
#import <Foundation/Foundation.h>

/** Record containing enum constant */
NS_SWIFT_SENDABLE
@interface DBConstantWithEnum : NSObject
- (nonnull instancetype)init NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)constantWithEnum;

+ (DBConstantEnum)constEnum;
@end

