// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from constant_enum.djinni
#ifdef __cplusplus
#ifndef __OBJC__

#include "constant_enum.hpp"
#import "DJIMarshal+Private.h"

#endif
#endif
