// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#import "DBSetRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SetRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Set<::djinni::String>::toCpp(obj.sset),
            ::djinni::Set<::djinni::I32>::toCpp(obj.iset)};
}

auto SetRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBSetRecord alloc] initWithSset:(::djinni::Set<::djinni::String>::fromCpp(cpp.sset))
                                        iset:(::djinni::Set<::djinni::I32>::fromCpp(cpp.iset))];
}

} // namespace djinni_generated
