// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from set.djinni

#import "DBSetRecord.h"


@implementation DBSetRecord

- (nonnull instancetype)initWithSset:(nonnull NSSet<NSString *> *)sset
                                iset:(nonnull NSSet<NSNumber *> *)iset
{
    if (self = [super init]) {
        _sset = [sset copy];
        _iset = [iset copy];
    }
    return self;
}

+ (nonnull instancetype)setRecordWithSset:(nonnull NSSet<NSString *> *)sset
                                     iset:(nonnull NSSet<NSNumber *> *)iset
{
    return [[self alloc] initWithSset:sset
                                 iset:iset];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p sset:%@ iset:%@>", self.class, (void *)self, self.sset, self.iset];
}

#endif
@end
