package djinni

import djinni.ast._
import djinni.generatorTools._
import djinni.meta._
import djinni.syntax.Loc
import djinni.writer.IndentWriter
import java.io.File

import scala.collection.mutable

class KotlinKmpGenerator(spec: Spec) extends Generator(spec) {

  private val kotlinMarshal = new KotlinMarshal(spec)
  private val kmpBridgePrefix: String = spec.kotlinKmpBridgePrefix.getOrElse("")
  private val resultExpr = "result"
  private val syntheticFile = new File("<generated>")

  private def syntheticIdent(name: String): Ident = Ident(name, syntheticFile, Loc(syntheticFile, 0, 0))

  override def generate(idl: Seq[TypeDecl]) {
    if (spec.kotlinKmpSwiftOutFolder.nonEmpty) spec.kotlinKmpIosOutFolder.foreach { folder =>
      writeKotlinFile(folder, kmpBridgePrefix + "SwiftBridgeBase.kt", "Swift export support", w => {
        w.wl("import kotlinx.cinterop.*")
        w.wl("import platform.Foundation.NSData")
        w.wl("import platform.Foundation.dataWithBytes")
        w.wl("import platform.posix.memcpy")
        w.wl
        w.wl(s"open class ${kmpBridgePrefix}SwiftBridgeBase")
        w.wl("@OptIn(ExperimentalForeignApi::class)")
        w.wl("fun djinniSwiftData(bytes: ByteArray): NSData = if (bytes.isEmpty()) NSData.dataWithBytes(null, 0u) else bytes.usePinned { NSData.dataWithBytes(it.addressOf(0), bytes.size.toULong()) }")
        w.wl("@OptIn(ExperimentalForeignApi::class)")
        w.wl("fun djinniSwiftBytes(data: NSData): ByteArray {")
        w.nested {
          w.wl("require(data.length <= Int.MAX_VALUE.toULong()) { \"Data exceeds Kotlin ByteArray capacity\" }")
          w.wl("return ByteArray(data.length.toInt()).also { if (it.isNotEmpty()) it.usePinned { pinned -> memcpy(pinned.addressOf(0), data.bytes, data.length) } }")
        }
        w.wl("}")
      })
    }
    for (td <- selectDecls(idl)) {
      td.body match {
        case r: Record => generateRecord(td, r)
        case e: Enum => generateEnum(td, e)
        case i: Interface => generateInterfaceDecl(td, i)
        case _ =>
      }
    }
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: Enum) {}

  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record) {}

  override def generateInterface(origin: String, ident: Ident, doc: Doc, typeParams: Seq[TypeParam], i: Interface) {}

  private def selectDecls(idl: Seq[TypeDecl]): Seq[TypeDecl] = {
    val byName = mutable.LinkedHashMap[String, TypeDecl]()
    for (td <- idl) {
      if (td.isInstanceOf[ExternTypeDecl]) {
        // Skip externs to avoid overwriting real definitions from their owning IDL file.
      } else {
        td.body match {
          case _: Record | _: Enum | _: Interface =>
            val name = canonicalName(td)
            byName.get(name) match {
              case Some(existing) =>
                val preferNew = td.isInstanceOf[InternTypeDecl] && !existing.isInstanceOf[InternTypeDecl]
                if (preferNew) {
                  byName(name) = td
                }
              case None =>
                byName(name) = td
            }
          case _ =>
        }
      }
    }
    byName.values.toSeq
  }

  private def canonicalName(td: TypeDecl): String = td match {
    case e: ExternTypeDecl => YamlGenerator.metaFromYaml(e).name
    case _ => td.ident.name
  }

  private def kmpTypeName(td: TypeDecl): String = kmpBridgePrefix + idJava.ty(canonicalName(td))
  private def externKmpPackage(e: MExtern): String = e.kmp.pkg
  private def externKmpBridgePrefix(e: MExtern): String =
    if (e.kmp.bridgePrefix.nonEmpty) e.kmp.bridgePrefix else kmpBridgePrefix
  private def externKmpTypeName(e: MExtern): String = externKmpBridgePrefix(e) + idJava.ty(e.name)
  private def externKmpFqTypeName(e: MExtern): String = {
    val typeName = externKmpTypeName(e)
    if (externKmpPackage(e).nonEmpty) s"${externKmpPackage(e)}.$typeName" else typeName
  }

  private def typeParamDecl(params: Seq[TypeParam]): String = {
    if (params.isEmpty) "" else params.map(p => idJava.typeParam(p.ident.name)).mkString("<", ", ", ">")
  }

  private def typeParamUse(params: Seq[TypeParam]): String = typeParamDecl(params)

  private def shortTypeName(typeName: String): String = {
    val idx = typeName.lastIndexOf('.')
    if (idx < 0) typeName else typeName.substring(idx + 1)
  }

  private def isEnum(tm: MExpr): Boolean = tm.base match {
    case d: MDef => d.defType == DEnum
    case e: MExtern => e.defType == DEnum
    case _ => false
  }

  private def isRecord(tm: MExpr): Boolean = tm.base match {
    case d: MDef => d.defType == DRecord
    case e: MExtern => e.defType == DRecord
    case _ => false
  }

  private def writeKotlinFile(folder: File, fileName: String, origin: String, f: IndentWriter => Unit, extraImports: Seq[String] = Seq.empty): Unit = {
    createFile(folder, fileName, (w: IndentWriter) => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl
      spec.kotlinKmpPackage.foreach(s => w.wl(s"package $s"))
      if (spec.kotlinKmpPackage.isDefined) {
        w.wl
      }
      extraImports.distinct.sorted.foreach(imp => w.wl(s"import $imp"))
      if (extraImports.nonEmpty) {
        w.wl
      }
      f(w)
    })
  }

  private def conversionImportsForTypes(types: Seq[MExpr]): Seq[String] = {
    val currentKmpPackage = spec.kotlinKmpPackage.getOrElse("")
    def externPackages(tm: MExpr): Set[String] = {
      val nested = tm.args.flatMap(externPackages).toSet
      tm.base match {
        case e: MExtern if externKmpPackage(e).nonEmpty && externKmpPackage(e) != currentKmpPackage =>
          nested + externKmpPackage(e)
        case _ => nested
      }
    }

    types
      .flatMap(externPackages)
      .toSet
      .toSeq
      .sorted
      .flatMap(pkg => Seq(s"$pkg.asKmp", s"$pkg.asPlatform"))
  }

  private def conversionImportsForRecord(r: Record): Seq[String] =
    conversionImportsForTypes(r.fields.map(_.ty.resolved))

  private def conversionImportsForInterface(i: Interface): Seq[String] = {
    val methodTypes = i.methods.flatMap { m =>
      m.params.map(_.ty.resolved) ++ m.ret.map(_.resolved).toSeq
    }
    conversionImportsForTypes(methodTypes ++ i.consts.map(_.ty.resolved))
  }

  private def generateRecord(td: TypeDecl, r: Record): Unit = {
    val name = kmpTypeName(td)
    val typeParams = typeParamDecl(td.params)
    val origin = td.origin
    val conversionImports = conversionImportsForRecord(r)

    spec.kotlinKmpCommonOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        w.w(s"expect class $name$typeParams(")
        if (r.fields.nonEmpty) {
          w.wl
          w.increase()
          for (f <- r.fields) {
            w.wl(s"${idJava.field(f.ident)}: ${kmpConstructorFieldType(f.ty.resolved)},")
          }
          w.decrease()
          w.w(")")
        } else {
          w.w(")")
        }
        w.wl(" {")
        w.increase()
        for (f <- r.fields) {
          w.wl(s"val ${idJava.field(f.ident)}: ${kmpFieldType(f.ty.resolved)}")
        }
        w.decrease()
        w.wl("}")
      })
    })

    spec.kotlinKmpAndroidOutFolder.foreach(folder => {
      val actualType = androidActualTypename(td) + typeParamUse(td.params)
      val useRecordWrapper = needsAndroidRecordWrapper(td, r)
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        if (useRecordWrapper) {
          w.w(s"actual class $name$typeParams actual public constructor(")
          if (r.fields.nonEmpty) {
            w.wl
            w.increase()
            for (f <- r.fields) {
              w.wl(s"${idJava.field(f.ident)}: ${kmpConstructorFieldType(f.ty.resolved)},")
            }
            w.decrease()
            w.w(")")
          } else {
            w.w(")")
          }
          w.wl(" {")
          w.increase()
          for (f <- r.fields) {
            val fieldName = idJava.field(f.ident)
            w.wl(s"actual val $fieldName: ${kmpFieldType(f.ty.resolved)} = ${kmpConstructorFieldInitializer(f.ty.resolved, fieldName)}")
          }
          w.decrease()
          w.wl("}")
          w.wl
          w.wl(s"public fun $name$typeParams.asPlatform(): $actualType = $actualType(")
          w.increase()
          for (f <- r.fields) {
            val fieldName = idJava.field(f.ident)
            w.wl(s"$fieldName = ${toPlatformExpr(f.ty.resolved, fieldName)},")
          }
          w.decrease()
          w.wl(")")
          w.wl(s"public fun $actualType.asKmp(): $name$typeParams = $name(")
          w.increase()
          for (f <- r.fields) {
            val fieldName = idJava.field(f.ident)
            val platformField = s"this.$fieldName"
            w.wl(s"$fieldName = ${fromPlatformExpr(f.ty.resolved, platformField)},")
          }
          w.decrease()
          w.wl(")")
        } else {
          w.wl(s"actual typealias $name$typeParams = $actualType")
          w.wl
          w.wl(s"public fun $name$typeParams.asPlatform(): $actualType = this")
          w.wl(s"public fun $actualType.asKmp(): $name$typeParams = this")
        }
      }, extraImports = conversionImports)
    })

    spec.kotlinKmpIosOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        w.w(s"actual class $name$typeParams actual constructor(")
        w.wl
        w.nested {
          for (f <- r.fields) {
            w.wl(s"actual val ${idJava.field(f.ident)}: ${kmpFieldType(f.ty.resolved)},")
          }
        }
        w.wl(")")
      })
    })
  }

  private def generateEnum(td: TypeDecl, e: Enum): Unit = {
    val name = kmpTypeName(td)
    val origin = td.origin

    spec.kotlinKmpCommonOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        w.w(s"expect enum class $name")
        w.braced {
          for (o <- normalEnumOptions(e)) {
            w.wl(idJava.enum(o.ident) + ",")
          }
        }
      })
    })

    spec.kotlinKmpAndroidOutFolder.foreach(folder => {
      val actualType = androidActualTypename(td)
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        w.wl(s"actual typealias $name = $actualType")
        w.wl
        w.wl(s"public fun $name.asPlatform(): $actualType = this")
        w.wl(s"public fun $actualType.asKmp(): $name = this")
      })
    })

    spec.kotlinKmpIosOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        w.w(s"actual enum class $name").braced {
          for (o <- normalEnumOptions(e)) w.wl(idJava.enum(o.ident) + ",")
        }
      })
    })
  }

  private def generateInterfaceDecl(td: TypeDecl, i: Interface): Unit = {
    val name = kmpTypeName(td)
    val origin = td.origin
    val typeParams = typeParamDecl(td.params)
    val typeParamsUse = typeParamUse(td.params)
    val hasStatics = i.methods.exists(_.static) || i.consts.nonEmpty
    val kmpImplementable = i.ext.java && i.ext.swift
    val classKind = !kmpImplementable || hasStatics
    val conversionImports = conversionImportsForInterface(i)

    spec.kotlinKmpCommonOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        if (classKind) {
          w.w(s"expect class $name$typeParams constructor(nativeHandle: Any)")
        } else {
          w.w(s"expect interface $name$typeParams")
        }
        w.braced {
          for (m <- i.methods if !m.static) {
            w.wl
            val params = methodParams(m)
            val retType = kmpReturnType(m.ret)
            val retSuffix = if (retType == "Unit") "" else s": $retType"
            w.wl(s"fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix")
          }
          if (classKind && (i.consts.nonEmpty || i.methods.exists(_.static))) {
            w.wl
            w.wl("companion object").braced {
              for (c <- i.consts) {
                val constType = kmpFieldType(c.ty.resolved)
                w.wl(s"val ${idJava.const(c.ident)}: $constType")
              }
              for (m <- i.methods if m.static) {
                w.wl
                val params = methodParams(m)
                val retType = kmpReturnType(m.ret)
                val retSuffix = if (retType == "Unit") "" else s": $retType"
                w.wl(s"fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix")
              }
            }
          }
        }
      })
    })

    spec.kotlinKmpAndroidOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        val platformTypeBaseFq = androidActualTypename(td)
        val platformTypeBase = shortTypeName(platformTypeBaseFq)
        val platformType = platformTypeBase + typeParamsUse
        w.wl(s"import $platformTypeBaseFq")
        w.wl
        if (classKind) {
          w.wl(s"actual class $name$typeParams actual public constructor(")
          w.increase()
          w.wl("nativeHandle: Any,")
          w.decrease()
          w.wl(") {")
          w.increase()
          w.wl("internal val nativeHandle: Any = nativeHandle")
          w.wl(s"private val native = nativeHandle as $platformType")
          for (m <- i.methods if !m.static) {
            w.wl
            val params = methodParams(m)
            val retType = kmpReturnType(m.ret)
            val retSuffix = if (retType == "Unit") "" else s": $retType"
            w.wl(s"actual fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix {")
            w.increase()
            val args = m.params.map(p => toPlatformExpr(p.ty.resolved, idJava.local(p.ident)))
            val call = s"native.${idJava.method(m.ident)}(${args.mkString(", ")})"
            if (retType == "Unit") {
              w.wl(call)
            } else {
              w.wl(s"val result = $call")
              w.wl(s"return ${fromPlatformExpr(m.ret.get.resolved, resultExpr)}")
            }
            w.decrease()
            w.wl("}")
          }
          if (i.consts.nonEmpty || i.methods.exists(_.static)) {
            w.wl
            w.wl("actual companion object").braced {
              for (c <- i.consts) {
                val constType = kmpFieldType(c.ty.resolved)
                val platformConst = s"$platformTypeBase.${idJava.const(c.ident)}"
                w.wl(s"actual val ${idJava.const(c.ident)}: $constType")
                w.wl(s"    get() = ${fromPlatformExpr(c.ty.resolved, platformConst)}")
              }
              for (m <- i.methods if m.static) {
                w.wl
                val params = methodParams(m)
                val retType = kmpReturnType(m.ret)
                val retSuffix = if (retType == "Unit") "" else s": $retType"
                w.wl(s"actual fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix {")
                w.increase()
                val args = m.params.map(p => toPlatformExpr(p.ty.resolved, idJava.local(p.ident)))
                val call = s"$platformTypeBase.${idJava.method(m.ident)}(${args.mkString(", ")})"
                if (retType == "Unit") {
                  w.wl(call)
                } else {
                  w.wl(s"val result = $call")
                  w.wl(s"return ${fromPlatformExpr(m.ret.get.resolved, resultExpr)}")
                }
                w.decrease()
                w.wl("}")
              }
            }
          }
          w.decrease()
          w.wl("}")
          w.wl
          w.wl(s"public fun $name$typeParams.asPlatform(): $platformType = nativeHandle as $platformType")
          w.wl(s"public fun $platformType.asKmp(): $name$typeParams = $name(this)")
        } else {
          w.wl(s"actual interface $name$typeParams")
          w.braced {
            for (m <- i.methods if !m.static) {
              w.wl
              val params = methodParams(m)
              val retType = kmpReturnType(m.ret)
              val retSuffix = if (retType == "Unit") "" else s": $retType"
              w.wl(s"actual fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix")
            }
          }
          w.wl
          val androidIsInterface = spec.javaGenInterface && !hasStatics && !i.ext.cpp
          val platformProxySuper = if (androidIsInterface) platformType else platformType + "()"
          w.wl(s"private class ${name}PlatformWrapper$typeParams(internal val nativeHandle: $platformType) : $name$typeParams")
          w.braced {
            for (m <- i.methods if !m.static) {
              w.wl
              val params = methodParams(m)
              val retType = kmpReturnType(m.ret)
              val retSuffix = if (retType == "Unit") "" else s": $retType"
              w.wl(s"override fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix {")
              w.increase()
              val args = m.params.map(p => toPlatformExpr(p.ty.resolved, idJava.local(p.ident)))
              val call = s"nativeHandle.${idJava.method(m.ident)}(${args.mkString(", ")})"
              if (retType == "Unit") {
                w.wl(call)
              } else {
                w.wl(s"val result = $call")
                w.wl(s"return ${fromPlatformExpr(m.ret.get.resolved, resultExpr)}")
              }
              w.decrease()
              w.wl("}")
            }
          }
          w.wl
          w.wl(s"private class ${name}PlatformProxy$typeParams(private val delegate: $name$typeParams) : $platformProxySuper")
          w.braced {
            for (m <- i.methods if !m.static) {
              w.wl
              val params = platformMethodParams(m)
              val retType = platformReturnType(m.ret)
              val retSuffix = if (retType == "Unit") "" else s": $retType"
              w.wl(s"override fun ${idJava.method(m.ident)}(${params.mkString(", ")})$retSuffix {")
              w.increase()
              val args = m.params.map(p => fromPlatformExpr(p.ty.resolved, idJava.local(p.ident)))
              val call = s"delegate.${idJava.method(m.ident)}(${args.mkString(", ")})"
              if (retType == "Unit") {
                w.wl(call)
              } else {
                w.wl(s"val result = $call")
                w.wl(s"return ${toPlatformExpr(m.ret.get.resolved, resultExpr)}")
              }
              w.decrease()
              w.wl("}")
            }
          }
          w.wl
          w.wl(s"public fun $name$typeParams.asPlatform(): $platformType = when (this) {")
          w.wl(s"    is ${name}PlatformWrapper$typeParams -> this.nativeHandle")
          w.wl(s"    else -> ${name}PlatformProxy(this)")
          w.wl("}")
          w.wl(s"public fun $platformType.asKmp(): $name$typeParams = ${name}PlatformWrapper(this)")
        }
      }, extraImports = conversionImports)
    })

    spec.kotlinKmpIosOutFolder.foreach(folder => {
      writeKotlinFile(folder, s"$name.kt", origin, w => {
        def signature(m: Interface.Method): String = {
          val ret = kmpReturnType(m.ret)
          s"fun ${idJava.method(m.ident)}(${methodParams(m).mkString(", ")})" + (if (ret == "Unit") "" else s": $ret")
        }
        if (classKind) {
          w.w(s"interface ${name}Native$typeParams").braced {
            for (m <- i.methods if !m.static) w.wl(signature(m))
          }
          w.wl
          w.w(s"actual class $name$typeParams actual constructor(nativeHandle: Any)").braced {
            w.wl(s"val native: ${name}Native$typeParamsUse = nativeHandle as ${name}Native$typeParamsUse")
            for (m <- i.methods if !m.static) {
              val args = m.params.map(p => idJava.local(p.ident)).mkString(", ")
              w.wl(s"actual ${signature(m)} = native.${idJava.method(m.ident)}($args)")
            }
            if (hasStatics) {
              w.w("actual companion object").braced {
                w.wl(s"private var factory: ${name}Factory? = null")
                w.wl(s"fun installFactory(value: ${name}Factory) { factory = value }")
                w.wl(s"""private fun installedFactory(): ${name}Factory = requireNotNull(factory) { "Swift bindings have not been installed for $name" }""")
                for (c <- i.consts) {
                  w.wl(s"actual val ${idJava.const(c.ident)}: ${kmpFieldType(c.ty.resolved)} get() = installedFactory().${idJava.const(c.ident)}")
                }
                for (m <- i.methods if m.static) {
                  val args = m.params.map(p => idJava.local(p.ident)).mkString(", ")
                  w.wl(s"actual ${signature(m)} = installedFactory().${idJava.method(m.ident)}($args)")
                }
              }
            }
          }
          if (hasStatics) {
            w.wl
            w.w(s"interface ${name}Factory").braced {
              for (c <- i.consts) w.wl(s"val ${idJava.const(c.ident)}: ${kmpFieldType(c.ty.resolved)}")
              for (m <- i.methods if m.static) w.wl(signature(m))
            }
          }
        } else {
          w.w(s"actual interface $name$typeParams").braced {
            for (m <- i.methods if !m.static) w.wl("actual " + signature(m))
          }
        }
      })
    })
  }

  private def androidActualTypename(td: TypeDecl): String = td match {
    case e: ExternTypeDecl => YamlGenerator.metaFromYaml(e).java.typename
    case _ => kotlinMarshal.fqTypename(td.ident, td.body)
  }

  private def kmpFieldType(tm: MExpr): String = {
    val name = kmpType(tm)
    if (kotlinMarshal.isEnumFlags(tm)) s"EnumSet<$name>" else name
  }

  private def kmpConstructorFieldType(tm: MExpr): String = {
    kmpFieldType(tm)
  }

  private def kmpConstructorFieldInitializer(tm: MExpr, fieldName: String): String = {
    fieldName
  }

  private def needsAndroidRecordWrapper(td: TypeDecl, r: Record): Boolean = {
    val rootName = canonicalName(td)
    r.fields.exists(f => needsAndroidRecordWrapperType(f.ty.resolved, Set(rootName)))
  }

  private def needsAndroidRecordWrapperType(tm: MExpr, seen: Set[String]): Boolean = {
    tm.base match {
      case MList | MMap | MSet | MDate =>
        true
      case MOptional | MArray =>
        tm.args.exists(arg => needsAndroidRecordWrapperType(arg, seen))
      case _ if meta.isInterface(tm) =>
        true
      case _ if isRecord(tm) =>
        true
      case _ =>
        false
    }
  }

  private def kmpReturnType(ret: Option[TypeRef]): String = ret.fold("Unit")(t => kmpFieldType(t.resolved))

  private def methodParams(m: Interface.Method): Seq[String] = {
    m.params.map(p => s"${idJava.local(p.ident)}: ${kmpFieldType(p.ty.resolved)}")
  }

  private def platformFieldType(tm: MExpr): String = {
    val name = platformType(tm)
    if (kotlinMarshal.isEnumFlags(tm)) s"EnumSet<$name>" else name
  }

  private def platformReturnType(ret: Option[TypeRef]): String =
    ret.fold("Unit")(t => platformFieldType(t.resolved))

  private def platformMethodParams(m: Interface.Method): Seq[String] =
    m.params.map(p => s"${idJava.local(p.ident)}: ${platformFieldType(p.ty.resolved)}")

  // Only Android converts to another Kotlin API. iOS exports its value types
  // and delegate contracts directly; the Swift adapter performs conversion.
  private def toPlatformExpr(tm: MExpr, expr: String): String = tm.base match {
    case MDate => s"java.util.Date($expr.toEpochMilliseconds())"
    case MOptional => s"$expr?.let { ${toPlatformExpr(tm.args.head, "it")} }"
    case MList => s"ArrayList($expr.map { ${toPlatformExpr(tm.args.head, "it")} })"
    case MSet => s"HashSet($expr.map { ${toPlatformExpr(tm.args.head, "it")} })"
    case MMap => s"HashMap($expr.map { ${toPlatformExpr(tm.args.head, "it.key")} to ${toPlatformExpr(tm.args(1), "it.value")} }.toMap())"
    case MArray => s"$expr.map { ${toPlatformExpr(tm.args.head, "it")} }.toTypedArray()"
    case _ if meta.isInterface(tm) || isRecord(tm) || isEnum(tm) => s"$expr.asPlatform()"
    case _ => expr
  }

  private def fromPlatformExpr(tm: MExpr, expr: String): String = tm.base match {
    case MDate => s"kotlin.time.Instant.fromEpochMilliseconds($expr.time)"
    case MOptional => s"$expr?.let { ${fromPlatformExpr(tm.args.head, "it")} }"
    case MList => s"ArrayList($expr.map { ${fromPlatformExpr(tm.args.head, "it")} })"
    case MSet => s"HashSet($expr.map { ${fromPlatformExpr(tm.args.head, "it")} })"
    case MMap => s"HashMap($expr.map { ${fromPlatformExpr(tm.args.head, "it.key")} to ${fromPlatformExpr(tm.args(1), "it.value")} }.toMap())"
    case MArray => s"$expr.map { ${fromPlatformExpr(tm.args.head, "it")} }.toTypedArray()"
    case _ if meta.isInterface(tm) || isRecord(tm) || isEnum(tm) => s"($expr as ${platformType(tm)}).asKmp()"
    case _ => expr
  }

  private def platformType(tm: MExpr): String = {
    def args(tm: MExpr) = if (tm.args.isEmpty) "" else tm.args.map(f).mkString("<", ", ", ">")
    def f(tm: MExpr): String = tm.base match {
      case MOptional => f(tm.args.head) + "?"
      case MArray => "Array<" + f(tm.args.head) + ">"
      case e: MExtern => e.java.typename + (if (e.java.generic) args(tm) else "")
      case p: MProtobuf => p.name
      case o =>
        val base = o match {
          case p: MPrimitive => p.kName
          case MString => "String"
          case MDate => "java.util.Date"
          case MBinary => "ByteArray"
          case MList => "ArrayList"
          case MSet => "HashSet"
          case MMap => "HashMap"
          case d: MDef => kotlinMarshal.fqTypename(syntheticIdent(d.name), d.body)
          case p: MParam => idJava.typeParam(p.name)
          case MVoid => "Void"
          case _ => throw new AssertionError("unreachable")
        }
        base + args(tm)
    }
    f(tm)
  }

  private def kmpType(tm: MExpr): String = {
    def args(tm: MExpr) = if (tm.args.isEmpty) "" else tm.args.map(f).mkString("<", ", ", ">")
    def f(tm: MExpr): String = {
      tm.base match {
        case MOptional =>
          assert(tm.args.size == 1)
          val arg = tm.args.head
          arg.base match {
            case p: MPrimitive => p.kName + "?"
            case MOptional => throw new AssertionError("nested optional?")
            case _ => f(arg) + "?"
          }
        case MArray => "Array<" + kmpType(tm.args.head) + ">"
        case e: MExtern => externKmpFqTypeName(e) + (if (e.java.generic) args(tm) else "")
        case p: MProtobuf => p.name
        case o =>
          val base = o match {
            case p: MPrimitive => p.kName
            case MString => "String"
            case MDate => "kotlin.time.Instant"
            case MBinary => "ByteArray"
            case MOptional => throw new AssertionError("optional should have been special cased")
            case MList => "List"
            case MSet => "Set"
            case MMap => "Map"
            case MArray => throw new AssertionError("array should have been special cased")
            case d: MDef => kmpBridgePrefix + idJava.ty(d.name)
            case e: MExtern => externKmpFqTypeName(e)
            case p: MProtobuf => p.name
            case p: MParam => idJava.typeParam(p.name)
            case MVoid => "Void"
          }
          base + args(tm)
      }
    }
    f(tm)
  }
}
