package djinni

import djinni.ast._
import djinni.generatorTools._
import djinni.meta._
import djinni.writer.IndentWriter

// Adapters live in a separate Swift target depending on both the exported Kotlin
// module and the native Swift API. Neither core module depends on the adapter.
class KotlinKmpSwiftGenerator(spec: Spec) extends Generator(spec) {
  private val swift = new SwiftMarshal(spec)
  private val prefix = spec.kotlinKmpBridgePrefix.getOrElse("")
  private val pkg = spec.kotlinKmpPackage.getOrElse("")
  private def qualified(p: String, n: String): String = if (p.isEmpty) n else p + "." + n
  private def kotlinName(name: String): String = qualified(pkg, prefix + idJava.ty(name))
  private def bridgeName(name: String): String = spec.swiftModule + "_" + idSwift.ty(name) + "Kmp"
  private def escape(name: String): String = swift.escapeSwiftIdent(name)
  private def kmpClass(i: Interface): Boolean = !(i.ext.java && i.ext.swift) || i.methods.exists(_.static) || i.consts.nonEmpty
  private def nativeClass(i: Interface): Boolean = i.ext.cpp && !i.ext.swift
  private def interface(tm: MExpr): Option[Interface] = tm.base match {
    case d: MDef => d.body match { case i: Interface => Some(i); case _ => None }
    case e: MExtern => e.body match { case i: Interface => Some(i); case _ => None }
    case _ => None
  }
  private def externalName(e: MExtern): String = qualified(e.kmp.pkg, (if (e.kmp.bridgePrefix.nonEmpty) e.kmp.bridgePrefix else prefix) + idJava.ty(e.name))
  private def kotlinType(tm: MExpr): String = tm.base match {
    case MOptional => val child = kotlinType(tm.args.head); (if (child.startsWith("any ")) s"($child)" else child) + "?"
    case MList | MArray => s"[${kotlinType(tm.args.head)}]"
    case MSet => s"Set<${kotlinType(tm.args.head)}>"
    case MMap => s"[${kotlinType(tm.args.head)}: ${kotlinType(tm.args(1))}]"
    case MDate => "kotlin.time.Instant"
    case MBinary => "kotlin.ByteArray"
    case d: MDef => (if (interface(tm).exists(i => !kmpClass(i))) "any " else "") + kotlinName(d.name)
    case e: MExtern => externalName(e)
    case _ => swift.fqTypename(tm)
  }
  private def bridge(tm: MExpr): String = tm.base match {
    case d: MDef => bridgeName(d.name)
    case e: MExtern => e.swift.module + "_" + e.swift.typename + "Kmp"
    case _ => throw new AssertionError("not a declared type")
  }
  private def convert(tm: MExpr, value: String, toKotlin: Boolean): String = {
    def child(t: MExpr, v: String) = convert(t, v, toKotlin)
    tm.base match {
      case MOptional => val c = child(tm.args.head, "$0"); if (c == "$0") value else s"$value.map { $c }"
      case MList | MArray => val c = child(tm.args.head, "$0"); if (c == "$0") value else s"$value.map { $c }"
      case MSet => val c = child(tm.args.head, "$0"); if (c == "$0") value else s"Set($value.map { $c })"
      case MMap =>
        val k = child(tm.args.head, "$0.key"); val v = child(tm.args(1), "$0.value")
        if (k == "$0.key" && v == "$0.value") value else s"Dictionary(uniqueKeysWithValues: $value.map { ($k, $v) })"
      case MDate if toKotlin => s"kotlin.time.Instant.Companion.shared.fromEpochMilliseconds(epochMilliseconds: Int64(($value.timeIntervalSince1970 * 1000).rounded()))"
      case MDate => s"Date(timeIntervalSince1970: Double($value.epochSeconds) + Double($value.nanosecondsOfSecond) / 1_000_000_000)"
      case MBinary if toKotlin => s"${qualified(pkg, "djinniSwiftBytes")}(data: $value as NSData)"
      case MBinary => s"${qualified(pkg, "djinniSwiftData")}(bytes: $value) as Data"
      case e: MExtern if e.swift.translator == "DataRefMarshaller" =>
        if (toKotlin) s"${qualified(e.kmp.pkg, "asKmp")}($value as NSData)" else s"${qualified(e.kmp.pkg, "asPlatform")}($value) as Data"
      case _: MDef | _: MExtern => s"${bridge(tm)}.${if (toKotlin) "toKotlin" else "toSwift"}($value)"
      case _ => value
    }
  }
  private def writeFile(ident: Ident, origin: String, types: Seq[MExpr], trailer: IndentWriter => Unit = _ => ())(body: IndentWriter => Unit): Unit = {
    def imports(tm: MExpr): Seq[String] = tm.args.flatMap(imports) ++ (tm.base match {
      case e: MExtern =>
        val adapters = if (e.swift.module.nonEmpty && e.swift.module != spec.swiftModule && e.swift.translator != "DataRefMarshaller" && e.swift.translator != "FutureMarshaller") Seq(e.swift.module + "KmpAdapters") else Seq.empty
        Seq(e.swift.module) ++ adapters
      case _ => Seq.empty
    })
    createFile(spec.kotlinKmpSwiftOutFolder.get, idSwift.ty(ident) + "+Kmp.swift", w => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      for (module <- (Seq("Foundation", spec.kotlinKmpSwiftModule, spec.swiftModule) ++ types.flatMap(imports)).filter(_.nonEmpty).distinct.sorted) w.wl("import " + module)
      w.wl
      w.w(s"public enum ${bridgeName(ident.name)}").braced { body(w) }
      trailer(w)
    })
  }
  override def generateModule(decls: Seq[InternTypeDecl]): Unit = {
    if (spec.skipGeneration) return
    val folder = spec.kotlinKmpSwiftOutFolder.get
    // IDL files are generated separately. Refresh the registration list from
    // this generator's own adapter files so the final pass includes every factory.
    val factories = folder.listFiles().toSeq.filter(_.getName.endsWith("+Kmp.swift")).flatMap { file =>
      val source = scala.io.Source.fromFile(file)
      val text = try source.mkString finally source.close()
      if (text.contains("public static func install()")) text.split("\n").find(_.startsWith("public enum ")).map(_.split(" ")(2)) else None
    }.distinct.sorted
    createFile(folder, spec.swiftModule + "KmpBindings.swift", w => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("import Foundation")
      w.w(s"public enum ${spec.swiftModule}KmpBindings").braced {
        w.w("public static func install()").braced { factories.foreach(f => w.wl(s"$f.install()")) }
        w.w("final class WeakCache").braced {
          w.wl("private let lock = NSRecursiveLock()")
          w.wl("private let entries = NSMapTable<AnyObject, AnyObject>(keyOptions: [.weakMemory, .objectPointerPersonality], valueOptions: .weakMemory)")
          w.w("func get(_ key: AnyObject, create: () -> AnyObject) -> AnyObject").braced {
            w.wl("lock.lock()")
            w.wl("defer { lock.unlock() }")
            w.wl("if let value = entries.object(forKey: key) { return value }")
            w.wl("let value = create()")
            w.wl("entries.setObject(value, forKey: key)")
            w.wl("return value")
          }
        }
      }
    })
  }

  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: Enum): Unit = {
    require(!e.flags, "KMP Swift flag adapters require a Kotlin Set contract")
    val native = swift.fqTypename(ident.name, e)
    val kotlin = kotlinName(ident.name)
    writeFile(ident, origin, Seq.empty, w => {
      w.wl("import KotlinRuntime")
      w.wl("// Kotlin 2.4.20 omits enum collection bridging. Remove when Swift export supplies this conformance.")
      w.w(s"extension $kotlin: @retroactive _ObjectiveCBridgeable").braced {
        w.wl("public typealias _ObjectiveCType = KotlinBase")
        w.w("public func _bridgeToObjectiveC() -> KotlinBase").braced {
          w.wl("KotlinBase(__externalRCRefUnsafe: __externalRCRef(), options: .asBestFittingWrapper)")
        }
        w.wl("private static let _djinniEnumCases = Dictionary(uniqueKeysWithValues: allCases.map { ($0._bridgeToObjectiveC(), $0) })")
        w.w("public static func _conditionallyBridgeFromObjectiveC(_ source: KotlinBase, result: inout Self?) -> Bool").braced {
          w.wl("result = _djinniEnumCases[source]")
          w.wl("return result != nil")
        }
        w.w("public static func _forceBridgeFromObjectiveC(_ source: KotlinBase, result: inout Self?)").braced {
          w.wl("precondition(_conditionallyBridgeFromObjectiveC(source, result: &result), \"Wrong Kotlin enum type\")")
        }
        w.w("public static func _unconditionallyBridgeFromObjectiveC(_ source: KotlinBase?) -> Self").braced {
          w.wl("var result: Self?")
          w.wl("_forceBridgeFromObjectiveC(source!, result: &result)")
          w.wl("return result!")
        }
      }
    }) { w =>
      for (toKotlin <- Seq(true, false)) {
        w.w(s"public static func ${if (toKotlin) "toKotlin" else "toSwift"}(_ value: ${if (toKotlin) native else kotlin}) -> ${if (toKotlin) kotlin else native}").braced {
          w.w("switch value").braced {
            for (option <- normalEnumOptions(e)) {
              val n = swift.enumName(option.ident.name)
              val k = escape(idJava.enum(option.ident))
              w.wl(s"case .${if (toKotlin) n else k}: return .${if (toKotlin) k else n}")
            }
            w.wl("@unknown default: fatalError(\"Unknown enum value at the Kotlin/Swift boundary\")")
          }
        }
      }
    }
  }
  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record): Unit = {
    require(params.isEmpty, "Generic KMP Swift record adapters are not supported")
    writeFile(ident, origin, r.fields.map(_.ty.resolved)) { w =>
      for (toKotlin <- Seq(true, false)) {
        val source = if (toKotlin) swift.fqTypename(ident.name, r) else kotlinName(ident.name)
        val target = if (toKotlin) kotlinName(ident.name) else swift.fqTypename(ident.name, r)
        w.w(s"public static func ${if (toKotlin) "toKotlin" else "toSwift"}(_ value: $source) -> $target").braced {
          val fields = r.fields.map { f =>
            val input = if (toKotlin) idSwift.field(f.ident) else escape(idJava.field(f.ident))
            val label = if (toKotlin) escape(idJava.field(f.ident)) else idSwift.field(f.ident)
            s"$label: ${convert(f.ty.resolved, "value." + input, toKotlin)}"
          }
          w.wl(s"return $target(${fields.mkString(", ")})")
        }
      }
    }
  }
  override def generateInterface(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], i: Interface): Unit = {
    require(params.isEmpty, "Generic KMP Swift interface adapters are not supported")
    val native = swift.fqTypename(ident.name, i)
    val kName = kotlinName(ident.name)
    val kType = (if (kmpClass(i)) "" else "any ") + kName
    val base = qualified(pkg, prefix + "SwiftBridgeBase")
    val properties = swift.properties(i)
    val setters = properties.flatMap(m => swift.setterFor(i, m))
    val types = i.methods.flatMap(m => m.params.map(_.ty.resolved) ++ m.ret.map(_.resolved)) ++ i.consts.map(_.ty.resolved)
    writeFile(ident, origin, types) { w =>
      w.wl(s"private static let kotlinCache = ${spec.swiftModule}KmpBindings.WeakCache()")
      if (!nativeClass(i)) w.wl(s"private static let swiftCache = ${spec.swiftModule}KmpBindings.WeakCache()")
      w.w(s"public static func toKotlin(_ value: $native) -> $kType").braced {
        if (!nativeClass(i)) w.wl("if let original = value as? ToSwift { return original._djinniValue }")
        val create = if (kmpClass(i)) s"$kName(nativeHandle: ToKotlin(value))" else "ToKotlin(value)"
        w.wl(s"return kotlinCache.get(value as AnyObject) { $create } as! $kType")
      }
      w.w(s"public static func toSwift(_ value: $kType) -> $native").braced {
        val handle = if (kmpClass(i)) "value.native" else "value"
        if (nativeClass(i)) w.wl(s"return ($handle as! ToKotlin)._djinniValue")
        else {
          w.wl(s"if let original = $handle as? ToKotlin { return original._djinniValue }")
          w.wl(s"return swiftCache.get(value as AnyObject) { ToSwift(value) } as! $native")
        }
      }
      def call(m: Interface.Method, toKotlin: Boolean): String = {
        val args = m.params.zipWithIndex.map { case (p, index) =>
          val arg = if (toKotlin) escape(idJava.local(p.ident)) else idSwift.local(p.ident)
          val label = if (toKotlin) { if (index == 0 && !(m.static && swift.isFactory(ident.name, m))) "" else idSwift.local(p.ident) + ": " } else escape(idJava.local(p.ident)) + ": "
          label + convert(p.ty.resolved, arg, !toKotlin)
        }
        if (toKotlin && properties.contains(m)) "self._djinniValue." + swift.propertyName(m)
        else if (toKotlin && setters.contains(m)) {
          val getter = properties.find(g => swift.setterFor(i, g).contains(m)).get
          "self._djinniValue." + swift.propertyName(getter) + " = " + convert(m.params.head.ty.resolved, escape(idJava.local(m.params.head.ident)), false)
        } else {
          val receiver = if (m.static) native + (if (nativeClass(i)) "" else "Factory") else "self._djinniValue"
          receiver + "." + (if (toKotlin) swift.swiftMethodName(m.ident.name) else escape(idJava.method(m.ident))) + args.mkString("(", ", ", ")")
        }
      }
      def body(m: Interface.Method, toKotlin: Boolean, invocation: String): Unit = {
        swift.futureValue(m) match {
          case Some(result) if toKotlin =>
            val future = m.ret.get.resolved.base.asInstanceOf[MExtern]
            val promise = externalName(future).stripSuffix("Future") + "Promise"
            w.wl(s"let promise = $promise()")
            w.w("Task").braced {
              w.w("do").braced {
                w.wl(s"let result = try await $invocation")
                w.wl(s"promise.setValue(value: ${convert(result, "result", true)})")
              }
              w.w("catch").braced { w.wl("promise.setException(message: (error as? DjinniError)?.errorMessage ?? String(describing: error))") }
            }
            w.wl("return promise.future()")
          case Some(result) =>
            w.wl(s"let result = try await $invocation.await()")
            w.wl(s"return ${convert(result, "(result as! " + kotlinType(result) + ")", false)}")
          case None =>
            val attempt = if (toKotlin && !spec.swiftNonThrowing && !setters.contains(m)) "try! " else ""
            m.ret match {
              case Some(t) => w.wl(s"let result = $attempt$invocation"); w.wl(s"return ${convert(t.resolved, "result", toKotlin)}")
              case None => w.wl(attempt + invocation)
            }
        }
      }
      def method(m: Interface.Method, toKotlin: Boolean): Unit = {
        val args = m.params.zipWithIndex.map { case (p, index) =>
          if (toKotlin) s"${escape(idJava.local(p.ident))}: ${kotlinType(p.ty.resolved)}"
          else (if (index == 0) "_ " else "") + s"${idSwift.local(p.ident)}: ${swift.fqTypename(p.ty.resolved)}"
        }
        val result = if (toKotlin) m.ret.map(t => kotlinType(t.resolved)).getOrElse("Void") else swift.futureValue(m).map(swift.fqTypename).getOrElse(swift.fqReturnType(m.ret))
        val effects = if (!toKotlin && swift.futureValue(m).nonEmpty) " async throws" else if (!toKotlin && !spec.swiftNonThrowing) " throws" else ""
        val name = if (toKotlin) escape(idJava.method(m.ident)) else swift.swiftMethodName(m.ident.name)
        w.w(s"func $name(${args.mkString(", ")})$effects -> $result").braced { body(m, toKotlin, call(m, toKotlin)) }
      }
      w.w(s"final class ToKotlin: $base, ${kName}${if (kmpClass(i)) "Native" else ""}").braced {
        w.wl(s"let _djinniValue: $native")
        w.wl(s"init(_ value: $native) { self._djinniValue = value; super.init() }")
        for (m <- i.methods if !m.static) method(m, true)
      }
      if (!nativeClass(i)) w.w(s"final class ToSwift: $native").braced {
        w.wl(s"let _djinniValue: $kType")
        w.wl(s"init(_ value: $kType) { self._djinniValue = value }")
        for (getter <- properties) {
          val ret = swift.futureValue(getter).map(swift.fqTypename).getOrElse(swift.fqReturnType(getter.ret))
          val effects = if (swift.futureValue(getter).nonEmpty) " async throws" else if (!spec.swiftNonThrowing) " throws" else ""
          w.w(s"var ${swift.propertyName(getter)}: $ret").braced {
            w.w("get" + effects).braced { body(getter, false, call(getter, false)) }
            swift.setterFor(i, getter).foreach { setter =>
              w.w("set").braced { w.wl(s"self._djinniValue.${escape(idJava.method(setter.ident))}(${escape(idJava.local(setter.params.head.ident))}: ${convert(setter.params.head.ty.resolved, "newValue", true)})") }
            }
          }
        }
        for (m <- i.methods if !m.static && !properties.contains(m) && !setters.contains(m)) method(m, false)
      }
      if (i.methods.exists(_.static) || i.consts.nonEmpty) {
        w.w(s"public static func install()").braced { w.wl(s"$kName.Companion.shared.installFactory(value: Factory())") }
        w.w(s"final class Factory: $base, ${kName}Factory").braced {
          for (c <- i.consts) w.wl(s"var ${escape(idJava.const(c.ident))}: ${kotlinType(c.ty.resolved)} { ${convert(c.ty.resolved, native + "." + idSwift.const(c.ident), true)} }")
          for (m <- i.methods if m.static) method(m, true)
        }
      }
    }
  }
}
