package djinni

import djinni.ast._
import djinni.generatorTools._
import djinni.meta._
import djinni.writer.IndentWriter
import java.io.File

/** Kotlin/Wasm uses typed JsAny imports; no Kotlin object crosses the JS ABI unconverted. */
class KotlinKmpWasmGenerator(spec: Spec, kmp: KotlinKmpGenerator) extends Generator(spec) {
  private val runtime = spec.kotlinKmpBridgePrefix.getOrElse("") + "DjinniWasm"
  override def generateEnum(origin: String, ident: Ident, doc: Doc, e: Enum) {}
  override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record) {}
  override def generateInterface(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], i: Interface) {}

  private def file(folder: File, name: String, origin: String)(body: IndentWriter => Unit): Unit =
    createFile(folder, name + ".kt", w => {
      w.wl("// AUTOGENERATED FILE - DO NOT MODIFY!")
      w.wl("// This file was generated by Djinni from " + origin)
      w.wl("@file:OptIn(kotlin.js.ExperimentalWasmJsInterop::class)")
      spec.kotlinKmpPackage.foreach(p => w.wl("package " + p))
      w.wl("import kotlin.js.*")
      w.wl
      body(w)
    })

  def generateRuntime(folder: File): Unit = file(folder, runtime, "KotlinKmpWasmGenerator") { w =>
    val code = """
object RUNTIME {
    class Handle(val value: JsAny)
    private var module: JsAny? = null
    private val proxies = mutableListOf<JsAny>()
    fun initialize(module: JsAny) { this.module = module }
    fun requireModule(): JsAny = checkNotNull(module) { "Initialize the Djinni Wasm module before using factories" }
    fun handle(value: JsAny?): Handle = Handle(requireNotNull(value))
    fun native(handle: Any): JsAny = (handle as Handle).value
    fun obj(): JsAny = wasmObject()
    fun get(value: JsAny?, name: String): JsAny? = wasmGet(requireNotNull(value), name)
    fun set(value: JsAny, name: String, field: JsAny?) { wasmSet(value, name, field) }
    fun index(value: JsAny?, index: Int): JsAny? = wasmIndex(requireNotNull(value), index)
    fun call(value: JsAny?, name: String, vararg args: JsAny?): JsAny? = wasmCall(requireNotNull(value), name, list(args.toList()))
    fun list(values: List<JsAny?>): JsAny {
        val result = wasmArray()
        values.forEach { wasmPush(result, it) }
        return result
    }
    fun array(value: JsAny?): List<JsAny?> {
        val array = wasmArrayFrom(requireNotNull(value))
        return List(wasmLength(array)) { wasmIndex(array, it) }
    }
    fun typedArray(kind: String, values: List<JsAny?>): JsAny = wasmTypedArray(kind, list(values))
    fun set(values: List<JsAny?>): JsAny = wasmSetFrom(list(values))
    fun map(values: List<JsAny?>): JsAny = wasmMapFrom(list(values))
    fun bytes(value: ByteArray): JsAny = typedArray("Uint8Array", value.map { number((it.toInt() and 255).toDouble()) })
    fun number(value: Double): JsAny = wasmNumber(value)
    fun number(value: JsAny?): Double = wasmToNumber(requireNotNull(value))
    fun long(value: Long): JsAny = wasmLong(value)
    fun long(value: JsAny?): Long = wasmToLong(requireNotNull(value))
    fun string(value: String): JsAny = wasmString(value)
    fun string(value: JsAny?): String = wasmToString(requireNotNull(value))
    fun boolean(value: Boolean): JsAny = wasmBoolean(value)
    fun boolean(value: JsAny?): Boolean = wasmToBoolean(requireNotNull(value))
    fun undefined(): JsAny? = wasmUndefined()
    fun callback(block: (List<JsAny?>) -> JsAny?): JsAny = wasmCallback { args -> block(array(args)) }
    fun proxy(owner: Any, type: String, create: () -> JsAny): JsAny {
        val iterator = proxies.iterator()
        while (iterator.hasNext()) {
            val entry = wasmDeref(iterator.next())
            if (entry == null) { iterator.remove(); continue }
            val cachedOwner = requireNotNull(get(entry, "owner")).unsafeCast<JsReference<Any>>().get()
            if (cachedOwner === owner && string(get(entry, "type")) == type) return requireNotNull(get(entry, "proxy"))
        }
        val result = create()
        proxies.add(wasmTrackProxy(result, owner.toJsReference(), type))
        return result
    }
}
private fun wasmObject(): JsAny = js("({})")
private fun wasmGet(value: JsAny, name: String): JsAny? = js("value[name]")
private fun wasmSet(value: JsAny, name: String, field: JsAny?): Unit = js("{ value[name] = field ?? undefined; }")
private fun wasmIndex(value: JsAny, index: Int): JsAny? = js("value[index]")
private fun wasmCall(value: JsAny, name: String, args: JsAny): JsAny? = js("value[name].apply(value, args.map(v => v ?? undefined))")
private fun wasmArray(): JsAny = js("[]")
private fun wasmPush(value: JsAny, item: JsAny?): Unit = js("{ value.push(item ?? undefined); }")
private fun wasmArrayFrom(value: JsAny): JsAny = js("Array.from(value)")
private fun wasmLength(value: JsAny): Int = js("value.length")
private fun wasmTypedArray(kind: String, values: JsAny): JsAny = js("new globalThis[kind](values)")
private fun wasmSetFrom(values: JsAny): JsAny = js("new Set(values)")
private fun wasmMapFrom(values: JsAny): JsAny = js("new Map(values)")
private fun wasmNumber(value: Double): JsAny = js("value")
private fun wasmToNumber(value: JsAny): Double = js("value")
private fun wasmLong(value: Long): JsAny = js("value")
private fun wasmToLong(value: JsAny): Long = js("value")
private fun wasmString(value: String): JsAny = js("value")
private fun wasmToString(value: JsAny): String = js("value")
private fun wasmBoolean(value: Boolean): JsAny = js("value")
private fun wasmToBoolean(value: JsAny): Boolean = js("value")
private fun wasmUndefined(): JsAny? = js("undefined")
private fun wasmCallback(block: (JsAny) -> JsAny?): JsAny = js("(...args) => block(args) ?? undefined")
private fun wasmDeref(reference: JsAny): JsAny? = js("reference.deref()")
private fun wasmTrackProxy(proxy: JsAny, owner: JsAny, type: String): JsAny = js("{ const entry = {proxy, owner, type}; Object.defineProperty(proxy, Symbol(), {value: entry}); return new WeakRef(entry); }")
""".trim.replace("RUNTIME", runtime)
    code.split("\n").foreach(w.wl(_))
  }

  private def toJs(tm: MExpr, expr: String): String = tm.base match {
    case MOptional => s"($expr)?.let { value -> ${toJs(tm.args.head, "value")} } ?: $runtime.undefined()"
    case p: MPrimitive if p.kName == "Long" => s"$runtime.long($expr)"
    case p: MPrimitive if p.kName == "Boolean" => s"$runtime.boolean($expr)"
    case _: MPrimitive => s"$runtime.number(($expr).toDouble())"
    case MString => s"$runtime.string($expr)"
    case MBinary => s"$runtime.bytes($expr)"
    case MArray =>
      val values = s"($expr).map { element -> ${toJs(tm.args.head, "element")} }"
      val arrays = Map("Byte" -> "Int8Array", "Short" -> "Int16Array", "Int" -> "Int32Array", "Long" -> "BigInt64Array", "Float" -> "Float32Array", "Double" -> "Float64Array")
      tm.args.head.base match {
        case p: MPrimitive if arrays.contains(p.kName) => s"""$runtime.typedArray("${arrays(p.kName)}", $values)"""
        case _ => s"$runtime.list($values)"
      }
    case MList => s"$runtime.list(($expr).map { element -> ${toJs(tm.args.head, "element")} })"
    case MSet => s"$runtime.set(($expr).map { element -> ${toJs(tm.args.head, "element")} })"
    case MMap => s"$runtime.map(($expr).map { (key, value) -> $runtime.list(listOf(${toJs(tm.args.head, "key")}, ${toJs(tm.args(1), "value")})) })"
    case e: MExtern if e.name == "future" => s"${kmp.jsConversionName(tm)}ToJs($expr) { item -> ${toJs(tm.args.head, "item")} }"
    case _: MDef | _: MExtern => s"${kmp.jsConversionName(tm)}ToJs($expr)"
    case _ => throw new IllegalArgumentException("Unsupported Kotlin/Wasm type: " + tm)
  }

  private def fromJs(tm: MExpr, expr: String): String = tm.base match {
    case MOptional => s"($expr)?.let { value -> ${fromJs(tm.args.head, "value")} }"
    case p: MPrimitive if p.kName == "Long" => s"$runtime.long($expr)"
    case p: MPrimitive if p.kName == "Boolean" => s"$runtime.boolean($expr)"
    case p: MPrimitive => s"$runtime.number($expr).to${p.kName}()"
    case MString => s"$runtime.string($expr)"
    case MBinary => s"$runtime.array($expr).map { $runtime.number(it).toInt().toByte() }.toByteArray()"
    case MList => s"$runtime.array($expr).map { element -> ${fromJs(tm.args.head, "element")} }"
    case MArray => s"$runtime.array($expr).map { element -> ${fromJs(tm.args.head, "element")} }.toTypedArray()"
    case MSet => s"$runtime.array($expr).map { element -> ${fromJs(tm.args.head, "element")} }.toHashSet()"
    case MMap => s"$runtime.array($expr).associate { entry -> ${fromJs(tm.args.head, s"$runtime.index(entry, 0)")} to ${fromJs(tm.args(1), s"$runtime.index(entry, 1)")} }.let { HashMap(it) }"
    case e: MExtern if e.name == "future" => s"${kmp.jsConversionName(tm)}FromJs($expr) { item -> ${fromJs(tm.args.head, "item")} }"
    case _: MDef | _: MExtern => s"${kmp.jsConversionName(tm)}FromJs($expr)"
    case _ => throw new IllegalArgumentException("Unsupported Kotlin/Wasm type: " + tm)
  }

  private def params(td: TypeDecl): String =
    if (td.params.isEmpty) "" else td.params.map(p => idJava.typeParam(p.ident.name)).mkString("<", ", ", ">")

  def generateRecord(folder: File, td: TypeDecl, r: Record): Unit = {
    val name = kmp.kmpTypeName(td)
    val tp = params(td)
    val ftp = if (tp.isEmpty) "" else tp + " "
    file(folder, name, td.origin) { w =>
      w.wl(s"actual class $name$tp actual constructor(${r.fields.map(f => s"actual val ${idJava.field(f.ident)}: ${kmp.kmpFieldType(f.ty.resolved)}").mkString(", ")})")
      w.wl(s"fun $ftp${name}ToJs(value: $name$tp): JsAny {")
      w.wl(s"    val result = $runtime.obj()")
      for (f <- r.fields) w.wl(s"""    $runtime.set(result, "${idJs.field(f.ident)}", ${toJs(f.ty.resolved, "value." + idJava.field(f.ident))})""")
      w.wl("    return result"); w.wl("}")
      w.wl(s"fun $ftp${name}FromJs(value: JsAny?): $name$tp = $name(")
      for (f <- r.fields) w.wl(s"    ${fromJs(f.ty.resolved, runtime + ".get(value, \"" + idJs.field(f.ident) + "\")")},")
      w.wl(")")
    }
  }

  def generateEnum(folder: File, td: TypeDecl, e: Enum): Unit = {
    val name = kmp.kmpTypeName(td)
    file(folder, name, td.origin) { w =>
      w.wl(s"actual enum class $name(val jsValue: Int) {")
      for ((o, n) <- normalEnumOptions(e).zipWithIndex) w.wl(s"    ${idJava.enum(o.ident)}(${if (e.flags) s"1 shl $n" else n.toString}),")
      w.wl("}")
      w.wl(s"fun ${name}ToJs(value: $name): JsAny = $runtime.number(value.jsValue.toDouble())")
      w.wl(s"fun ${name}FromJs(value: JsAny?): $name = $name.entries.firstOrNull { it.jsValue == $runtime.number(value).toInt() }")
      w.wl(s"""    ?: throw IllegalArgumentException("Unknown $name value")""")
    }
  }

  def generateInterface(folder: File, td: TypeDecl, i: Interface, classKind: Boolean): Unit = {
    val name = kmp.kmpTypeName(td)
    val tp = params(td)
    val ftp = if (tp.isEmpty) "" else tp + " "
    def method(w: IndentWriter, m: Interface.Method, modifier: String, receiver: String): Unit = {
      w.wl(s"$modifier fun ${idJava.method(m.ident)}(${kmp.methodParams(m).mkString(", ")}): ${kmp.kmpReturnType(m.ret)} {")
      val args = m.params.map(p => toJs(p.ty.resolved, idJava.local(p.ident)))
      val call = s"""$runtime.call($receiver, "${idJs.method(m.ident)}"${if (args.isEmpty) "" else ", " + args.mkString(", ")})"""
      m.ret match {
        case Some(ret) => w.wl(s"    val result = $call"); w.wl(s"    return ${fromJs(ret.resolved, "result")}")
        case None => w.wl(s"    $call")
      }
      w.wl("}")
    }
    file(folder, name, td.origin) { w =>
      if (classKind) {
        w.wl(s"actual class $name$tp actual constructor(nativeHandle: Any) {")
        w.increase(); w.wl(s"internal val native: JsAny = $runtime.native(nativeHandle)")
        for (m <- i.methods if !m.static) method(w, m, "actual", "native")
        if (i.consts.nonEmpty || i.methods.exists(_.static)) {
          w.wl("actual companion object {"); w.increase()
          val path = spec.wasmNamespace.toSeq.flatMap(_.split('.')) :+ idJs.ty(td.ident)
          val receiver = path.foldLeft(s"$runtime.requireModule()")((base, part) => s"""$runtime.get($base, "$part")""")
          for (c <- i.consts) w.wl(s"actual val ${idJava.const(c.ident)}: ${kmp.kmpFieldType(c.ty.resolved)} get() = ${fromJs(c.ty.resolved, runtime + ".get(" + receiver + ", \"" + idJs.const(c.ident) + "\")")}")
          for (m <- i.methods if m.static) method(w, m, "actual", receiver)
          w.decrease(); w.wl("}")
        }
        w.decrease(); w.wl("}")
        w.wl(s"fun $ftp${name}ToJs(value: $name$tp): JsAny = value.native")
        w.wl(s"fun $ftp${name}FromJs(value: JsAny?): $name$tp = $name($runtime.handle(value))")
      } else {
        w.wl(s"actual interface $name$tp {")
        for (m <- i.methods) w.wl(s"    actual fun ${idJava.method(m.ident)}(${kmp.methodParams(m).mkString(", ")}): ${kmp.kmpReturnType(m.ret)}")
        w.wl("}")
        w.wl(s"private class ${name}WasmWrapper$tp(val native: JsAny) : $name$tp {"); w.increase()
        for (m <- i.methods) method(w, m, "override", "native")
        w.decrease(); w.wl("}")
        w.wl(s"fun $ftp${name}FromJs(value: JsAny?): $name$tp = ${name}WasmWrapper(requireNotNull(value))")
        w.wl(s"fun $ftp${name}ToJs(value: $name$tp): JsAny {"); w.increase()
        w.wl(s"if (value is ${name}WasmWrapper$tp) return value.native")
        w.wl(s"""return $runtime.proxy(value, "$name") {"""); w.increase()
        w.wl(s"val result = $runtime.obj()")
        for (m <- i.methods) {
          w.wl(s"""$runtime.set(result, "${idJs.method(m.ident)}", $runtime.callback { args ->"""); w.increase()
          val args = m.params.zipWithIndex.map { case (p, n) => fromJs(p.ty.resolved, s"args[$n]") }
          val call = s"value.${idJava.method(m.ident)}(${args.mkString(", ")})"
          m.ret match {
            case Some(ret) => w.wl(s"val returned = $call"); w.wl(toJs(ret.resolved, "returned"))
            case None => w.wl(call); w.wl(s"$runtime.undefined()")
          }
          w.decrease(); w.wl("})")
        }
        w.wl("result"); w.decrease(); w.wl("}"); w.decrease(); w.wl("}")
      }
    }
  }
}
