package djinni

import java.io.File
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.{Files, StandardCopyOption}
import java.security.MessageDigest
import java.util.Locale
import scala.collection.mutable
import scala.collection.JavaConversions._
import djinni.generatorTools.GenerateException

/** Buffer the complete invocation before touching outputs. The manifest records content ownership. */
class TreeOutput(manifest: File, root: File) {
  private val outputs = mutable.LinkedHashMap[String, Array[Byte]]()
  private val paths = mutable.Map[String, String]()
  private def hash(bytes: Array[Byte]) = MessageDigest.getInstance("SHA-256").digest(bytes).map(b => f"${b & 255}%02x").mkString
  private def fail(message: String): Nothing = throw GenerateException(message)

  def add(file: File, bytes: Array[Byte]): Unit = {
    val path = file.getCanonicalPath
    paths.put(path.toLowerCase(Locale.ROOT), path).foreach(previous =>
      fail(s"Output collision: $previous and $path"))
    outputs(path) = bytes
  }

  def commit(): Unit = {
    val header = "djinni-tree-v1\t" + root.getCanonicalPath
    val previous = if (manifest.exists) {
      val lines = Files.readAllLines(manifest.toPath, UTF_8).toVector
      if (lines.headOption != Some(header)) fail("Manifest belongs to another source root: " + manifest)
      lines.tail.map { line =>
        val parts = line.split("\t", 2)
        if (parts.length != 2 || !parts(0).matches("[0-9a-f]{64}") || !new File(parts(1)).isAbsolute)
          fail("Invalid output manifest: " + manifest)
        parts(1) -> parts(0)
      }.toMap
    } else Map.empty[String, String]

    if (paths.contains(manifest.getCanonicalPath.toLowerCase(Locale.ROOT))) fail("Output collides with manifest: " + manifest)
    // Refuse to overwrite or remove files edited since our previous successful invocation.
    for (path <- (previous.keySet ++ outputs.keySet).toSeq.sorted) {
      val file = new File(path)
      if (file.exists) {
        val content = Files.readAllBytes(file.toPath)
        val digest = hash(content)
        val preamble = new String(content.take(512), UTF_8)
        val adoptGenerated = !previous.contains(path) && outputs.contains(path) &&
          (preamble.startsWith("// AUTOGENERATED FILE - DO NOT MODIFY!\n// This file was generated by Djinni") ||
           preamble.startsWith("# AUTOGENERATED FILE - DO NOT MODIFY!\n# This file was generated by Djinni"))
        if (!previous.get(path).contains(digest) && !outputs.get(path).exists(b => hash(b) == digest) && !adoptGenerated)
          fail("Refusing to replace unowned or modified file: " + path)
      }
    }
    val entries = outputs.toSeq.sortBy(_._1)
    val manifestBytes = (header + "\n" + entries.map { case (path, bytes) => hash(bytes) + "\t" + path + "\n" }.mkString).getBytes(UTF_8)
    // Prepare replacement files on the destination filesystem, then rename each atomically.
    val staged = mutable.ArrayBuffer[(java.nio.file.Path, java.nio.file.Path)]()
    try {
      for ((file, bytes) <- entries.map { case (p, b) => (new File(p), b) } :+ (manifest.getCanonicalFile, manifestBytes)) {
        if (!file.exists || !java.util.Arrays.equals(Files.readAllBytes(file.toPath), bytes)) {
          Files.createDirectories(file.toPath.getParent)
          val temp = Files.createTempFile(file.toPath.getParent, ".djinni-", ".tmp")
          staged += ((temp, file.toPath))
          Files.write(temp, bytes)
        }
      }
      for ((temp, destination) <- staged if destination != manifest.getCanonicalFile.toPath)
        Files.move(temp, destination, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
      for (path <- previous.keySet.diff(outputs.keySet).toSeq.sorted) Files.deleteIfExists(new File(path).toPath)
      staged.filter(_._2 == manifest.getCanonicalFile.toPath).foreach { case (temp, destination) =>
        Files.move(temp, destination, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
      }
    } finally staged.foreach { case (temp, _) => Files.deleteIfExists(temp) }
  }
}
